## default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: never
    output:
      ansi:
        enabled: always
  datasource:
    url: jdbc:postgresql://mouse.db.elephantsql.com:5432/trsdjhyx
    username: ${POSTGRES_USR}
    password: ${POSTGRES_PWD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  data:
    mongodb:
      uri:  mongodb+srv://${MONGODB_USR}:${MONGODB_PWD}@ajajanas.twyihs3.mongodb.net/test
      database: test

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR