name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup jdk-17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: jfs-lab-cloud-reviews-0.0.1-SNAPSHOT.jar
          path: ./target/jfs-lab-cloud-reviews-0.0.1-SNAPSHOT.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jfs-lab-cloud-reviews-0.0.1-SNAPSHOT

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.CLIENT_INFO }}

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: JakhongirsAppName
          package: 'jfs-lab-cloud-reviews-0.0.1-SNAPSHOT.jar'

      # Azure logout
      - name: logout
        run: |
          az logout